// this should export an object only
export const headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36',
    'X-Permitted-Cross-Domain-Policies': 'master-only',
    'sec-ch-ua': '"Not/A)Brand";v="99", "Google Chrome";v="115", "Chromium";v="115"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-platform': '"Windows"',
}

export const commonSupplierParams: ParamsArray = {
    activeType: 'active',
    batchSize: 5,
    categoryCode: [],
    certCondition: {},
    departmentCode: [],
    filterOutDisqualifiedMatrix: false,
    includeFacet: true,
    includeLegalAddress: false,
    includeMatrix: false,
    includeOrderingAddresses: true,
    includeRemittanceAddresses: true,
    isBulkQualification: false,
    isErpIntegrated: null,
    isFactory: false,
    isMQEnhancementFlow: false,
    keyword: '',
    mainVendorsOnly: true,
    overallRiskScoreLevel: [],
    preferredLevel: [],
    purchasingUnitCodes: [],
    qualificationStatus: [],
    realmName: 'JCD',
    regionCode: [],
    registrationStatus: [],
    registrationUpdateStatus: [],
    searchQualificationAndRegistrationStatusAsAWhole: false,
    smProcessStatus: [],
    smVendorIds: [],
    spqFilterAnswerRequests: [],
  };

