  
  const commonParams: ParamsArray = {
    activeType: 'active',
    batchSize: 5,
    categoryCode: [],
    certCondition: {},
    departmentCode: [],
    filterOutDisqualifiedMatrix: false,
    includeFacet: true,
    includeLegalAddress: false,
    includeMatrix: false,
    includeOrderingAddresses: true,
    includeRemittanceAddresses: true,
    isBulkQualification: false,
    isErpIntegrated: null,
    isFactory: false,
    isMQEnhancementFlow: false,
    keyword: '',
    mainVendorsOnly: true,
    overallRiskScoreLevel: [],
    preferredLevel: [],
    purchasingUnitCodes: [],
    qualificationStatus: [],
    realmName: 'JCD',
    regionCode: [],
    registrationStatus: [],
    registrationUpdateStatus: [],
    searchQualificationAndRegistrationStatusAsAWhole: false,
    smProcessStatus: [],
    smVendorIds: [],
    spqFilterAnswerRequests: [],
  };
  
  export { commonParams };